---
title: "Uplift Models Evaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

## Conversion Prediction

```{r message=FALSE, warning=FALSE, include=FALSE}

library(ggplot2)
library(caret)
library(dplyr)
library(reshape2)
####################################################
# Uplift DT Rzepakowski et. al 2012
####################################################

source('DecisionTreeImplementation.R')
source('Evaluation Methods.R')
source('Separate Model Approach.R')
source('CausalTree.R')
source('Causal Forest.R')

set.seed(1234)

#Data import
email <- read.csv('Data/Email.csv')

email$men_treatment <- ifelse(email$segment=='Mens E-Mail',1,0)
email$women_treatment <- ifelse(email$segment=='Womens E-Mail',1,0)
email$control <- ifelse(email$segment=='No E-Mail',1,0)
email$mens <- as.factor(email$mens)
email$womens <- as.factor(email$womens)
email$newbie <- as.factor(email$newbie)

email$conversion <- email$spend <- email$segment <- NULL
```

### Rzepakowski 2012 Tree

```{r data_prep, eval=TRUE}
response <- 'visit'
control <- 'control'

set.seed(1234)
# Split into test and train data
idx <- createDataPartition(y = email[ , response], p=0.3, list = FALSE)

train <- email[-idx, ]

test <- email[idx, ]

# Partition training data for pruning
p_idx <- createDataPartition(y = train[ , response], p=0.3, list = FALSE)

val <- train[p_idx,]
train <- train[-p_idx,]

treatment_list <- c('men_treatment','women_treatment')
test_list <- set_up_tests(train[,c("recency","history_segment","history","mens","womens","zip_code",
                                   "newbie","channel")],TRUE)

```


```{r fit_tree, eval=F}

raw_tree <- build_tree(train,0,100,treatment_list,response,control,test_list,normalize = T)

pruned_tree <- prune_tree(raw_tree,val,treatment_list,test_list,response,control) #conversion

# add to the result df the outcome, assignment and calculate uplift for each T
pred <- predict.dt.as.df(pruned_tree, test)


### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/rzp tree pred.csv', row.names = FALSE)
```

```{r}
pred <- read.csv('Predictions/rzp tree pred.csv')

# Expected Response per targeted customers
exp_outcome_rzp <- new_expected_outcome(test,response,control,treatment_list,pred$Treatment)
exp_inc_outcome_rzp <- new_expected_quantile_response(test,response,control,treatment_list,pred)
overall_matched_rzp <- sum(pred$Treatment==pred$Assignment)/nrow(pred)
perc_matched_rzp <- perc_matched(pred)

rzp_tree_exp_conv <- expected_percentile_response(pred)

rzp_tree_mat_conv <- qini_curve(pred, "control")
```


### Simple Criterion

```{r fit_tree, eval=F}

raw_tree <- build_tree(train,0,100,treatment_list,response,'control',test_list,criterion = 2)

pruned_tree <- simple_prune_tree(raw_tree,val,treatment_list,test_list,response,control)

# add to the result df the outcome, assignment and calculate uplift for each T
pred <- predict.dt.as.df(pruned_tree, test)


### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/rzp tree pred simple.csv', row.names = FALSE)
```

```{r}
pred <- read.csv('Predictions/rzp tree pred simple.csv')

# Expected Response per targeted customers
exp_outcome_simple <- new_expected_outcome(test,response,control,treatment_list,pred$Treatment)
exp_inc_outcome_simple <- new_expected_quantile_response(test,response,control,treatment_list,pred)
overall_matched_simple <- sum(pred$Treatment==pred$Assignment)/nrow(pred)
perc_matched_simple <- perc_matched(pred)

rzp_tree_exp_conv_simple <- expected_percentile_response(pred)

rzp_tree_mat_conv_simple <- qini_curve(pred, "control")
```

### Simple Forest
```{r fit_tree, eval=F}

forest <- parallel_build_forest(train,val,treatment_list,response,'control',n_trees = 200,n_features = 4,criterion = 2, pruning = T)

pred <- parallel_predict_forest_df(forest, test)


### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/simple forest.csv', row.names = FALSE)
```

```{r}
pred <- read.csv('Predictions/simple forest.csv')

# Expected Response per targeted customers
exp_outcome_simple_forest <- new_expected_outcome(test,response,control,treatment_list,pred$Treatment)
exp_inc_outcome_simple_forest <- new_expected_quantile_response(test,response,control,treatment_list,pred)
overall_matched_simple_forest <- sum(pred$Treatment==pred$Assignment)/nrow(pred)
perc_matched_simple_forest <- perc_matched(pred)

simple_forest_exp_conv <- expected_percentile_response(pred)

simple_forest_mat_conv <- qini_curve(pred, "control")
```
### Rzp Forest
```{r fit_tree, eval=F}

forest <- parallel_build_forest(train,val,treatment_list,response,'control',n_trees = 200,n_features = 3,criterion = 1, pruning = F,normalize = T)

pred <- parallel_predict_forest_df(forest, test)


### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/rzp forest.csv', row.names = FALSE)
```

```{r}
pred <- read.csv('Predictions/rzp forest.csv')

# Expected Response per targeted customers
exp_outcome_rzp_forest <- new_expected_outcome(test,response,control,treatment_list,pred$Treatment)
exp_inc_outcome_rzp_forest <- new_expected_quantile_response(test,response,control,treatment_list,pred)
overall_matched_rzp_forest <- sum(pred$Treatment==pred$Assignment)/nrow(pred)
perc_matched_rzp_forest <- perc_matched(pred)

rzp_forest_exp_conv <- expected_percentile_response(pred)

rzp_forest_mat_conv <- qini_curve(pred, "control")
```


### Causal Tree

```{r, eval=FALSE}
causal_pred <- causalTreePredicitons(train, test, treatment_list, response)
write.csv(causal_pred, "Predictions/causal tree pred.csv", row.names = FALSE)

```


```{r}
# Evaluate pre saved Causal Tree results
causal_pred <- read.csv("Predictions/causal tree pred.csv")

exp_outcome_c_tree <- new_expected_outcome(test,response,control,treatment_list,causal_pred$Treatment)
exp_inc_outcome_c_tree <- new_expected_quantile_response(test,response,control,treatment_list,causal_pred)
overall_matched_causal <- sum(causal_pred$Treatment==causal_pred$Assignment)/nrow(causal_pred)
perc_matched_causal <- perc_matched(causal_pred)

c_tree_exp_conv <- expected_percentile_response(causal_pred)

c_tree_mat_conv <- qini_curve(causal_pred, "control")

```

### Causal Forest

```{r, eval=FALSE}
causal_forest_pred <- causalForestPredicitons(train, test, treatment_list, response)

causal_forest_pred[ , "uplift_men_treatment"] <- causal_forest_pred[ , 1] - causal_forest_pred[ , 3]
causal_forest_pred[ , "uplift_women_treatment"] <- causal_forest_pred[ , 2] - causal_forest_pred[ , 3]
causal_forest_pred[ , "Treatment"] <- colnames(causal_forest_pred)[apply(causal_forest_pred[, 1:3], 1, which.max)]

causal_forest_pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
causal_forest_pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(causal_forest_pred, "Predictions/causal forest conv pred.csv", row.names = FALSE)
```

```{r}
# Evaluate pre saved Causal Tree results
causal_forest_pred <- read.csv("Predictions/causal forest conv pred.csv")

exp_outcome_c_forest <- new_expected_outcome(test,response,control,treatment_list,causal_forest_pred$Treatment)
exp_inc_outcome_c_forest <- new_expected_quantile_response(test,response,control,treatment_list,causal_forest_pred)
overall_matched_causal_forest <- sum(as.character(causal_forest_pred$Treatment)==as.character(causal_forest_pred$Assignment))/nrow(causal_forest_pred)
perc_matched_causal_forest <- perc_matched(causal_forest_pred)

c_forest_exp_conv <- expected_percentile_response(causal_forest_pred)

c_forest_mat_conv <- qini_curve(causal_forest_pred, "control")

```

### Separate Model Approach

```{r}
# Import data and creat Train / Test splits
data <-  read.csv('Data/Email.csv')

## Prepare data to only include independent variables, treatment assignment and dependent variable
# Possible for conversion or visit

#data$visit <- NULL      
data$conversion <- NULL      
data$spend <- NULL

## Set these values depending on the dataset 
# Treatment column in data
treatment <- "segment"
# Response column
response <-  "visit"
# String Level of the control Level in Treatment column
control_level <- "No E-Mail"

treatments <- levels(as.factor(data[, treatment]))
# remove the control level from treatments
treatments <- treatments[! treatments %in% c(control_level)]

train_split <- data[-idx , ]
train_data <- list()
# make train_data list for each T
for(x in treatments){
  t_data <- train_split[train_split[, treatment] == x, ]
  
  # Remove the treatment column from training data
  t_data <- t_data[ , names(t_data) != treatment]
  
  # Each Training Set as one element in list
  train_data <- append(train_data, list(x = t_data[-idx, ]))
}
# Assign Treatment Names to Train Sets
names(train_data) <- treatments
# Add control group
t_data <- train_split[train_split[, treatment] == control_level, ]
t_data <- t_data[ , names(t_data) != treatment]
train_data <- append(train_data, list(Control = t_data[-idx, ]))

# write.csv(train_data$`Mens E-Mail`, 'Mens Train.csv', row.names = F)
# write.csv(train_data$`Womens E-Mail`, 'Womens Train.csv', row.names = F)
# write.csv(train_data$Control, 'Control Train.csv', row.names = F)

# Test Data
test_data <- data[idx , ]


#################
## Decision Tree
models_clas_dt <- dt_models(train_data, response, "class")

# Calculated Upflift for each individual and Treatment and chosen Treatment
pred_sma_con_dt <- tree_sma_uplift(models_clas_dt, test_data, response, treatment, control_level, "class")

# Expected Response per targeted customers



sma_dt_conv_exp <- expected_percentile_response(pred_sma_con_dt)

sma_dt_conv_mat <- qini_curve(pred_sma_con_dt, "Control")

#################
## Logit

# Creates k + 1 Logit models for binary response
models_logit <- logit_models(train_data, response)

## Evaluate Models on Test data
# Calculated Upflift for each individual and Treatment and chosen Treatment
predictions_logit <- logit_x_model_predictions(models_logit, test_data, response, treatment, control_level)

# Zhao 
sma_logit_conv_exp <- expected_percentile_response(predictions_logit)

sma_logit_conv_mat <- qini_curve(predictions_logit, "Control")

#################
## Random Forest
rf_models <- rf_models(train_data, response, "class")

rf_pred_class <- tree_sma_uplift(rf_models, test_data, response, treatment, control_level, "class")

# Expected Response per targeted customers
sma_rf_conv_exp <- expected_percentile_response(rf_pred_class)
sma_rf_conv_mat <- qini_curve(rf_pred_class, "Control")


sma_rf_conv_exp$Model <- sma_rf_conv_mat$Model <- "RF"
sma_dt_conv_exp$Model <- sma_dt_conv_mat$Model <- "DT"
sma_logit_conv_exp$Model <- sma_logit_conv_mat$Model <- "Logit"

```




### Model Comparison
```{r}
temp_df = data.frame(models=c("C_Forest","C_Tree","Rzp_Tree","Rzp_Forest","Simple_Tree","Simple_Forest"),values = c(exp_outcome_c_forest,exp_outcome_c_tree,exp_outcome_rzp,exp_outcome_rzp_forest,exp_outcome_simple,exp_outcome_simple_forest))

p<-ggplot(data=temp_df, aes(x=reorder(models, values), y=values)) +
  geom_bar(stat="identity")
p
```


```{r}
temp_vec <- rep(seq(0,1,0.1),6)
name_vec <- c(rep("C_Forest",11),rep("C_Tree",11),rep("Rzp_Tree",11),rep("Rzp_Forest",11),rep("Simple_Tree",11),rep("Simple_Forest",11))
temp_results <- cbind(c(exp_inc_outcome_c_forest,exp_inc_outcome_c_tree,exp_inc_outcome_rzp,exp_inc_outcome_rzp_forest,exp_inc_outcome_simple,exp_inc_outcome_simple_forest))
temp_df <- data.frame(cbind(temp_vec,temp_results,name_vec))
colnames(temp_df) <- c("Percentile","Expected_Outcome","Model")
temp_df$Expected_Outcome <- as.numeric(as.character(temp_df$Expected_Outcome))

p <-  melt(temp_df, id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=0.5 ) +
  labs(
    color="Base Learner",
    title = "All Models - Men's Treatment Curve",
    y = "Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()
p
```
```{r}
temp_df = data.frame(models=c("C_Forest","C_Tree","Rzp_Tree","Rzp_Forest","Simple_Tree","Simple_Forest"),values = c(overall_matched_causal_forest,overall_matched_causal,overall_matched_rzp,overall_matched_rzp_forest,overall_matched_simple,overall_matched_simple_forest))

p<-ggplot(data=temp_df, aes(x=reorder(models, values), y=values)) +
  geom_bar(stat="identity")
p
```



```{r}
temp_vec <- rep(seq(0,1,0.1),6)
name_vec <- c(rep("C_Tree",10),rep("C_Forest",10),rep("Rzp_Tree",10),rep("Rzp_Forest",10),rep("Simple_Tree",10),rep("Simple_Forest",10))
temp_results <- cbind(c(perc_matched_causal,perc_matched_causal_forest,perc_matched_rzp,perc_matched_rzp_forest,perc_matched_simple,perc_matched_simple_forest))
temp_df <- data.frame(cbind(temp_vec,temp_results,name_vec))
colnames(temp_df) <- c("Percentile","Matched","Model")
temp_df$Matched <- as.numeric(as.character(temp_df$Matched))

p <-  melt(temp_df, id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=0.5 ) +
  labs(
    color="Models",
    title = "Percentage Matched in each Decile",
    y = "Percentage Matched",
    x ="Decile"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()
p

```





```{r}
# Separate Male and Women Treatment

sma_rf_conv_exp$Model <- sma_rf_conv_mat$Model <- "SMA-RF"
sma_dt_conv_exp$Model <- sma_dt_conv_mat$Model <- "SMA-DT"
sma_logit_conv_exp$Model <- sma_logit_conv_mat$Model <- "SMA-Logit"
rzp_tree_exp_conv$Model<- rzp_tree_mat_conv$Model <- "Rzp-Tree"
rzp_forest_exp_conv$Model <- rzp_forest_mat_conv$Model <- "Rzp-Forest"
rzp_tree_exp_conv_simple$Model<- rzp_tree_mat_conv_simple$Model <- "Rzp-Tree Simple"

c_tree_exp_conv$Model<- c_tree_mat_conv$Model <- "Causal-Tree"
c_forest_exp_conv$Model<- c_forest_mat_conv$Model <- "Causal-Forest"

# Random line
men_total_increase <- mean(test[test$men_treatment == 1, response]) - mean(test[ test$control == 1, response])
women_total_increase <- mean(test[test$women_treatment == 1, response]) - mean(test[ test$control == 1, response])

dynamic_total_increase <- mean(test[test$control == 0, response]) - mean(test[ test$control == 1, response])


random_conv_mat <- data.frame(Percentile = sma_rf_conv_mat$Percentile
                              , mens = cumsum(rep(men_total_increase / nrow(sma_rf_conv_mat), nrow(sma_rf_conv_mat))) 
                              , womens = cumsum(rep(women_total_increase / nrow(sma_rf_conv_mat), nrow(sma_rf_conv_mat))) 
                              , max_t = cumsum(rep(dynamic_total_increase / nrow(sma_rf_conv_mat), nrow(sma_rf_conv_mat))) 
                              ,  Model='Random')


colnames(random_conv_mat)[2] <- colnames(rzp_tree_mat_conv)[2] <- colnames(rzp_tree_mat_conv_simple)[2] <- colnames(rzp_forest_mat_conv)[2]  <- colnames(c_forest_mat_conv)[2] <- colnames(c_tree_mat_conv)[2] <- "Mens E-Mail"
colnames(random_conv_mat)[3] <-colnames(rzp_tree_mat_conv)[3] <-colnames(rzp_tree_mat_conv_simple)[3] <-colnames(rzp_forest_mat_conv)[3]  <- colnames(c_forest_mat_conv)[3] <- colnames(c_tree_mat_conv)[3] <- "Womens E-Mail"
colnames(random_conv_mat)[4] <- "max T"

melt(rbind(
            sma_logit_conv_mat[, c("Percentile","Model","Mens E-Mail")], 
            sma_dt_conv_mat[, c("Percentile","Model","Mens E-Mail")], 
            sma_rf_conv_mat[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_mat_conv[, c("Percentile","Model","Mens E-Mail")],
            rzp_tree_mat_conv_simple[, c("Percentile","Model","Mens E-Mail")],
            rzp_forest_mat_conv[, c("Percentile","Model","Mens E-Mail")],
            c_tree_mat_conv[, c("Percentile","Model","Mens E-Mail")],
            c_forest_mat_conv[, c("Percentile","Model","Mens E-Mail")],
            random_conv_mat[, c("Percentile","Model","Mens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Base Learner",
    title = "All Models - Men's Treatment Curve",
    y = "Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()

melt(rbind(
          sma_logit_conv_mat[, c("Percentile","Model","Womens E-Mail")], 
          sma_dt_conv_mat[, c("Percentile","Model","Womens E-Mail")], 
          sma_rf_conv_mat[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_mat_conv[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_mat_conv_simple[, c("Percentile","Model","Womens E-Mail")],
          rzp_forest_mat_conv[, c("Percentile","Model","Womens E-Mail")],
          c_tree_mat_conv[, c("Percentile","Model","Womens E-Mail")],
          c_forest_mat_conv[, c("Percentile","Model","Womens E-Mail")],
          random_conv_mat[, c("Percentile","Model","Womens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Base Learner",
    title = "All Models - Women's Treatment Curve",
    y = "Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()

```

```{r}
# Expected Outcome
melt(rbind(
  sma_logit_conv_exp[, c("Percentile","Model","Expected Outcome")], 
  sma_dt_conv_exp[, c("Percentile","Model","Expected Outcome")], 
  sma_rf_conv_exp[, c("Percentile","Model","Expected Outcome")], 
  rzp_tree_exp_conv[, c("Percentile","Model","Expected Outcome")], 
  rzp_tree_exp_conv_simple[, c("Percentile","Model","Expected Outcome")], 
  rzp_forest_exp_conv[, c("Percentile","Model","Expected Outcome")],
  c_tree_exp_conv[, c("Percentile","Model","Expected Outcome")]
  ), 
  id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1  ) +
  labs(
    color="Model",
    title = "Expected Outcome",
    y = "Expected Outcome",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()

```


## Spent Prediction

```{r rzp_tree_spent}
email <- read.csv('Data/Email.csv')

email$men_treatment <- ifelse(email$segment=='Mens E-Mail',1,0)
email$women_treatment <- ifelse(email$segment=='Womens E-Mail',1,0)
email$control <- ifelse(email$segment=='No E-Mail',1,0)
email$mens <- as.factor(email$mens)
email$womens <- as.factor(email$womens)
email$newbie <- as.factor(email$newbie)

email$visit <- email$conversion <- email$segment <- NULL

response <- 'spend'

train <- email[-idx, ]

test <- email[idx, ]

# Partition training data for pruning
p_idx <- createDataPartition(y = train[ , response], p=0.3, list = FALSE)

val <- train[p_idx,]
train <- train[-p_idx,]

treatment_list <- c('men_treatment','women_treatment')
test_list <- set_up_tests(train[,c("recency","history_segment","history","mens","womens","zip_code",
                                   "newbie","channel")],TRUE)

```


### Causal Tree

```{r, eval=FALSE}
causal_pred <- causalTreePredicitons(train, test, treatment_list, response)


write.csv(causal_pred, "Predictions/causal tree spend pred.csv", row.names = FALSE)

```

```{r}
causal_pred <- read.csv('Predictions/causal tree spend pred.csv')

c_tree_exp_spend <- expected_percentile_response(causal_pred)

c_tree_mat_spend <- qini_curve(causal_pred, "control")

```



```{r, eval=FALSE}
## Raw tree still 

raw_tree <- build_tree(train,0,100,treatment_list,response,'control',test_list, divergence = "EucDistance")

# takes a lot of time..
#conversion
pruned_tree <- prune_tree(raw_tree,val,treatment_list,test_list,response,control) 

# add to the result df the outcome, assignment and calculate uplift for each T
pred <- predict.dt.as.df(pruned_tree, test)

### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/rzp tree spend pred.csv', row.names = FALSE)
```


```{r}
pred <- read.csv('Predictions/rzp tree spend pred.csv')

# Expected Response per targeted customers
rzp_tree_exp_spend <- expected_percentile_response(pred)

rzp_tree_mat_spend <- qini_curve(pred, "control")
```

### Simple Criterion

```{r, eval=FALSE}
## Raw tree still 

raw_tree <- build_tree(train,0,100,treatment_list,response,'control',test_list, divergence = "EucDistance",
                        criterion = 2)

# Partition training data for pruning
p_idx <- createDataPartition(y = train[ , response], p=0.3, list = FALSE)

pruned_tree <- simple_prune_tree(raw_tree,val,treatment_list,test_list,response,control)

# add to the result df the outcome, assignment and calculate uplift for each T
pred <- predict.dt.as.df(pruned_tree, test)

### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/simple tree spend pred.csv', row.names = FALSE)
```


```{r}
pred <- read.csv('Predictions/simple tree spend pred.csv')

# Expected Response per targeted customers
rzp_tree_exp_spend_simple <- expected_percentile_response(pred)

rzp_tree_mat_spend_simple <- qini_curve(pred, "control")
```


### Forest
```{r fit_tree, eval=F}
forest <- parallel_build_forest(train,val,treatment_list,response,'control',n_trees = 50,n_features = 4,criterion = 1,pruning = T, divergence = "EucDistance")

# takes a lot of time..
#conversion

# add to the result df the outcome, assignment and calculate uplift for each T
pred <- parallel_predict_forest_df(forest, test)

### Results Preparation to bring into equal format
# Calculate Uplift for each T
pred[ , "uplift_men_treatment"] <- pred[ , 1] - pred[ , 3]
pred[ , "uplift_women_treatment"] <- pred[ , 2] - pred[ , 3]
pred[ , "Treatment"] <- colnames(pred)[apply(pred[, 1:3], 1, which.max)]

pred[ , "Outcome"] <- test[, response]
# get the actual assignment from test data
pred[ , "Assignment"] <- colnames(test)[apply(test[, 10:12], 1, which.max) + 9]

write.csv(pred, 'Predictions/rzp forest spend.csv', row.names = FALSE)
```

```{r}
pred <- read.csv('Predictions/rzp forest spend.csv')

# Expected Response per targeted customers
rzp_forest_exp_spend <- expected_percentile_response(pred)

rzp_forest_mat_spend <- qini_curve(pred, "control")
```




```{r, eval=TRUE}
data <-  read.csv('Data/Email.csv')

## Prepare data to only include independent variables, treatment assignment and dependent variable
# Possible for conversion or visit

data$visit <- NULL      
data$conversion <- NULL

## Set these values depending on the dataset 
treatment <- "segment"
response <-  "spend" 
control_level <- "No E-Mail"

# creates k + 1 train test sets (for each T and control model)
treatments <- levels(as.factor(data[, treatment]))
# remove the control level from treatments
treatments <- treatments[! treatments %in% c(control_level)]

train_split <- data[-idx , ]
train_data <- list()
# make train_data list for each T
for(x in treatments){
  t_data <- train_split[train_split[, treatment] == x, ]
  
  # Remove the treatment column from training data
  t_data <- t_data[ , names(t_data) != treatment]
  
  # Each Training Set as one element in list
  train_data <- append(train_data, list(x = t_data[-idx, ]))
}
# Assign Treatment Names to Train Sets
names(train_data) <- treatments
# Add control group
t_data <- train_split[train_split[, treatment] == control_level, ]
t_data <- t_data[ , names(t_data) != treatment]
train_data <- append(train_data, list(Control = t_data[-idx, ]))

# Test Data
test_data <- data[idx , ]

## Decision Tree
models_dt <- dt_models(train_data, response, "anova")

# Calculated Upflift for each individual and Treatment and chosen Treatment
pred_sma_spend_dt <- tree_sma_uplift(models_dt, test_data, response, treatment, control_level, "anova")
# Expected Response per targeted customers
sma_dt_exp_spend <- expected_percentile_response(pred_sma_spend_dt)

sma_dt_mat_spend <- qini_curve(pred_sma_spend_dt, "Control")


#################
## Random Forest
rf_models <- rf_models(train_data, response, "anova")

rf_pred_spend <- tree_sma_uplift(rf_models, test_data, response, treatment, control_level, "anova")

colnames(rf_pred_spend)[1] <- "Mens E-Mail"
colnames(rf_pred_spend)[2] <- "Womens E-Mail"

colnames(rf_pred_spend)[4] <- "uplift_Mens E-Mail"
colnames(rf_pred_spend)[5] <- "uplift_Womens E-Mail"

# Expected Response per targeted customers
sma_rf_exp_spend <- expected_percentile_response(rf_pred_spend)

sma_rf_mat_spend <- qini_curve(rf_pred_spend, "Control")

```


```{r output_spend_comparison}

sma_rf_exp_spend$Model <- sma_rf_mat_spend$Model <- "SMA-RF"
sma_dt_exp_spend$Model <- sma_dt_mat_spend$Model <- "SMA-DT"

rzp_tree_exp_spend$Model<- rzp_tree_mat_spend$Model <- "Rzp-Tree"
rzp_forest_exp_spend$Model<- rzp_forest_mat_spend$Model <- "Rzp-Forest"
rzp_tree_exp_spend_simple$Model<- rzp_tree_mat_spend_simple$Model <- "Rzp-Tree Simple"

c_tree_exp_spend$Model<- c_tree_mat_spend$Model <- "Causal-Tree"


# Random line
men_total_increase <- mean(test[test$men_treatment == 1, response]) - mean(test[ test$control == 1, response])
women_total_increase <- mean(test[test$women_treatment == 1, response]) - mean(test[ test$control == 1, response])

random_spend_mat <- data.frame(Percentile = sma_rf_mat_spend$Percentile, mens = cumsum(rep(men_total_increase / nrow(sma_rf_mat_spend), nrow(sma_rf_mat_spend))) , womens = cumsum(rep(women_total_increase / nrow(sma_rf_mat_spend), nrow(sma_rf_mat_spend))) ,  Model='Random')



colnames(random_spend_mat)[2] <- colnames(rzp_tree_mat_spend_simple)[2] <- colnames(rzp_tree_mat_spend)[2] <- colnames(rzp_forest_mat_spend)[2] <- colnames(c_tree_mat_spend)[2] <- "Mens E-Mail"
colnames(random_spend_mat)[3] <-colnames(rzp_tree_mat_spend_simple)[3] <- colnames(rzp_tree_mat_spend)[3] <- colnames(rzp_forest_mat_spend)[3] <- colnames(c_tree_mat_spend)[3] <-"Womens E-Mail"


## Display of results only for SMA models
melt(rbind(
            sma_dt_mat_spend[, c("Percentile","Model","Mens E-Mail")], 
            sma_rf_mat_spend[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_mat_spend[, c("Percentile","Model","Mens E-Mail")], 
            rzp_forest_mat_spend[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_mat_spend_simple[, c("Percentile","Model","Mens E-Mail")], 
            c_tree_mat_spend[, c("Percentile","Model","Mens E-Mail")],
            random_spend_mat[, c("Percentile","Model","Mens E-Mail")])
     , id.vars  =c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
   
  
  geom_line(aes(y = value, group= Model, color= Model), size=1  ) +
  labs(
    color="Base Learner",
    title = "All Models - Men's Treatment Curve",
    y = "Spend Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()

melt(rbind(sma_dt_mat_spend[, c("Percentile","Model","Womens E-Mail")], 
            sma_rf_mat_spend[, c("Percentile","Model","Womens E-Mail")], 
            rzp_tree_mat_spend[, c("Percentile","Model","Womens E-Mail")], 
            rzp_forest_mat_spend[, c("Percentile","Model","Womens E-Mail")], 
            rzp_tree_mat_spend_simple[, c("Percentile","Model","Womens E-Mail")], 
            c_tree_mat_spend[, c("Percentile","Model","Womens E-Mail")],
            random_spend_mat[, c("Percentile","Model","Womens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1  ) +
  labs(
    color="Base Learner",
    title = "All Models - Women's Treatment Curve",
    y = "Spend Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()

```


```{r}
# Expected Outcome
melt(rbind(
  sma_dt_exp_spend[, c("Percentile","Model","Expected Outcome")], 
  sma_rf_exp_spend[, c("Percentile","Model","Expected Outcome")], 
  rzp_tree_exp_spend[, c("Percentile","Model","Expected Outcome")],
  rzp_forest_exp_spend[, c("Percentile","Model","Expected Outcome")],
  rzp_tree_exp_spend_simple[, c("Percentile","Model","Expected Outcome")],
  c_tree_exp_spend[, c("Percentile","Model","Expected Outcome")]
  ), 
  id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  
  geom_line(aes(y = value, group= Model, color= Model), size=1  ) +
  labs(
    color="Model",
    title = "Expected Spend Outcome",
    y = "Expected Outcome",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  theme_light()
```
