---
title: "Uplift Models Evaluation"
output: html_document
---


```{r setup, include=T}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_chunk$set(cache.extra = set.seed(123))
```

## Conversion Prediction

```{r message=FALSE, warning=FALSE, include=FALSE}
library(ggplot2)
library(caret)
library(dplyr)
library(reshape2)

source('Evaluation Methods.R')
```



```{r}
## Graph setting

line_size = 1
uplift_colors <- c('#984ea3','red', '#4daf4a', '#377eb8', '#a65628')
exp_colors <- c('#984ea3', '#4daf4a', '#377eb8', '#a65628')

uplift_lty <- c("solid","dashed","solid","solid","solid")

```


## Conversion

```{r}
# Expected Response per targeted customers
rzp_tree_exp_conv <- read.csv('CSV/rzp_tree_exp_conv.csv')
rzp_tree_up_conv <- read.csv('CSV/rzp_tree_up_conv.csv')

rzp_tree_exp_conv_simple <- read.csv('CSV/simple_tree_exp_conv.csv')
rzp_tree_up_conv_simple <- read.csv('CSV/simple_tree_up_conv.csv')

rzp_forest_exp_conv <- read.csv('CSV/rzp_forest_exp_conv.csv')
rzp_forest_up_conv <- read.csv('CSV/rzp_forest_up_conv.csv')

rzp_forest_exp_conv_simple <- read.csv('CSV/simple_forest_exp_conv.csv')
rzp_forest_up_conv_simple <- read.csv('CSV/simple_forest_up_conv.csv')

c_forest_exp_conv <- read.csv('CSV/c_forest_exp_conv.csv')
c_forest_up_conv <- read.csv('CSV/c_forest_up_conv.csv')

sma_rf_conv_exp <- read.csv('CSV/sma_rf_exp_conv.csv')
sma_rf_conv_up <- read.csv('CSV/sma_rf_up_conv.csv')

sma_rf_conv_exp$Model <- sma_rf_conv_up$Model <- "SMA-RF"
rzp_tree_exp_conv$Model<- rzp_tree_up_conv$Model <- "Rzp-Tree"
rzp_tree_exp_conv_simple$Model<- rzp_tree_up_conv_simple$Model <- "Rzp-Tree Simple"
c_forest_exp_conv$Model<- c_forest_up_conv$Model <- "Causal-Forest"

rzp_forest_exp_conv$Model<- rzp_forest_up_conv$Model <- "Rzp-Forest"
rzp_forest_exp_conv_simple$Model<- rzp_forest_up_conv_simple$Model <- "Rzp-Forest Simple"

### Random Assignment

dat <- read.csv('Email.csv')
response <- "conversion"

dat$men_treatment <- ifelse(dat$segment=='Mens E-Mail',1,0)
dat$women_treatment <- ifelse(dat$segment=='Womens E-Mail',1,0)
dat$control <- ifelse(dat$segment=='No E-Mail',1,0)

# Test data with 5-fold CV
N_test_data <- nrow(dat) * (1/5)

# Random line
men_total_increase <- (mean(dat[dat$men_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data
women_total_increase <- (mean(dat[dat$women_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data

dynamic_total_increase <- (mean(dat[dat$control == 0, response]) - mean(dat[ dat$control == 1, response]) ) *  N_test_data

random_conv_up <- data.frame(Percentile = sma_rf_conv_up$Percentile                              
                             , mens = c(0,cumsum(rep(men_total_increase / (nrow(sma_rf_conv_up) - 1), nrow(sma_rf_conv_up) - 1 )) )
                              , womens = c(0,cumsum(rep(women_total_increase / (nrow(sma_rf_conv_up) -1), nrow(sma_rf_conv_up) - 1))) 
                              , max_t = c(0,cumsum(rep(dynamic_total_increase / (nrow(sma_rf_conv_up) -1), nrow(sma_rf_conv_up) - 1)) )
                              ,  Model='Random')


## Cumulative AVG
# random_conv_up <- data.frame(Percentile = sma_rf_conv_up$Percentile
#                               , mens = cumsum(rep(men_total_increase / nrow(sma_rf_conv_up), nrow(sma_rf_conv_up))) 
#                               , womens = cumsum(rep(women_total_increase / nrow(sma_rf_conv_up), nrow(sma_rf_conv_up))) 
#                               , max_t = cumsum(rep(dynamic_total_increase / nrow(sma_rf_conv_up), nrow(sma_rf_conv_up))) 
#                               ,  Model='Random')

colnames(random_conv_up)[2] <- colnames(rzp_tree_up_conv)[2] <- colnames(c_forest_up_conv)[2]<- colnames(rzp_tree_up_conv_simple)[2] <- colnames(sma_rf_conv_up)[2] <- "Mens E-Mail"
colnames(random_conv_up)[3] <-colnames(rzp_tree_up_conv)[3] <- colnames(c_forest_up_conv)[3]<- colnames(rzp_tree_up_conv_simple)[3] <- colnames(sma_rf_conv_up)[3] <- "Womens E-Mail"
colnames(random_conv_up)[4] <- "combined"


```

```{r eval=FALSE, include=FALSE}

melt(rbind(
            sma_rf_conv_up[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_up_conv[, c("Percentile","Model","Mens E-Mail")],
            rzp_tree_up_conv_simple[, c("Percentile","Model","Mens E-Mail")],
            c_forest_up_conv[, c("Percentile","Model","Mens E-Mail")],
            random_conv_up[, c("Percentile","Model","Mens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Model",
    title = "Men's Treatment (Test Data Population: 12,800)",
    y = "Cumulated Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()

melt(rbind(
          sma_rf_conv_up[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_up_conv[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_up_conv_simple[, c("Percentile","Model","Womens E-Mail")],
          c_forest_up_conv[, c("Percentile","Model","Womens E-Mail")],
          random_conv_up[, c("Percentile","Model","Womens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=line_size) +
  labs(
    color="Model",
    title = "Women's Treatment (Test Data Population: 12,800)",
    y = "Cumulated Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()

```



```{r}
# Combined Treatments
melt(rbind(
          sma_rf_conv_up[, c("Percentile","Model","combined")], 
          rzp_tree_up_conv[, c("Percentile","Model","combined")], 
          rzp_tree_up_conv_simple[, c("Percentile","Model","combined")],
          c_forest_up_conv[, c("Percentile","Model","combined")],
          #rzp_forest_up_conv_simple[, c("Percentile","Model","combined")],
          #rzp_forest_up_conv[, c("Percentile","Model","combined")],
          random_conv_up[, c("Percentile","Model","combined")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model, lty = Model), size=1 ) +
  labs(
    color="Model",
    title = "Conversion - Male & Female Treatment (Test Data Size: 12,800)",
    y = "Cumulated Number of Converted Customers",
    x ="Amount of Treated"
  ) +
  scale_linetype_manual(values = uplift_lty)+
  scale_color_manual(values = uplift_colors)+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()
```




```{r}
# Expected Outcome
melt(rbind(
  sma_rf_conv_exp[, c("Percentile","Model","Expected.Outcome")], 
  rzp_tree_exp_conv[, c("Percentile","Model","Expected.Outcome")], 
  rzp_tree_exp_conv_simple[, c("Percentile","Model","Expected.Outcome")], 
  #rzp_forest_exp_conv_simple[, c("Percentile","Model","Expected.Outcome")], 
  #rzp_forest_exp_conv[, c("Percentile","Model","Expected.Outcome")], 
  c_forest_exp_conv[, c("Percentile","Model","Expected.Outcome")]
  ), 
  id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=line_size  ) +
  labs(
    color="Model",
    title = "Expected Conversion",
    y = "Expected Conversion per Customer",
    x ="Amount of Treated"
  ) +
  scale_color_manual(values = exp_colors)+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()

```


## Spend

```{r}
# Expected Response per targeted customers
rzp_tree_exp_spend <- read.csv('CSV/rzp_tree_exp_spend.csv')
rzp_tree_up_spend <- read.csv('CSV/rzp_tree_up_spend.csv')

simple_tree_exp_spend <- read.csv('CSV/simple_tree_exp_spend.csv')
simple_tree_up_spend <- read.csv('CSV/simple_tree_up_spend.csv')

simple_forest_exp_spend <- read.csv('CSV/simple_forest_exp_spend.csv')
simple_forest_up_spend <- read.csv('CSV/simple_forest_up_spend.csv')

rzp_forest_exp_spend <- read.csv('CSV/rzp_forest_exp_spend.csv')
rzp_forest_up_spend <- read.csv('CSV/rzp_forest_up_spend.csv')

c_forest_exp_spend <- read.csv('CSV/c_forest_exp_spend.csv')
c_forest_up_spend <- read.csv('CSV/c_forest_up_spend.csv')

sma_rf_exp_spend <- read.csv('CSV/sma_rf_exp_spend.csv')
sma_rf_up_spend <- read.csv('CSV/sma_rf_up_spend.csv')


sma_rf_exp_spend$Model <- sma_rf_up_spend$Model <- "SMA-RF"
rzp_tree_exp_spend$Model<- rzp_tree_up_spend$Model <- "Rzp-Tree"
simple_tree_exp_spend$Model<- simple_tree_up_spend$Model <- "Rzp-Tree Simple"
c_forest_exp_spend$Model<- c_forest_up_spend$Model <- "Causal-Forest"

rzp_forest_exp_spend$Model<- rzp_forest_up_spend$Model <- "Rzp-Forest"
simple_forest_exp_spend$Model<- simple_forest_up_spend$Model <- "Rzp-Forest Simple"



dat <- read.csv('Email.csv')
response <- "spend"

dat$men_treatment <- ifelse(dat$segment=='Mens E-Mail',1,0)
dat$women_treatment <- ifelse(dat$segment=='Womens E-Mail',1,0)
dat$control <- ifelse(dat$segment=='No E-Mail',1,0)


# Test data with 5-fold CV
N_test_data <- nrow(dat) * (1/5)

men_total_increase <- (mean(dat[dat$men_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data
women_total_increase <- (mean(dat[dat$women_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data

dynamic_total_increase <- (mean(dat[dat$control == 0, response]) - mean(dat[ dat$control == 1, response]) ) *  N_test_data

random_spend <- data.frame(Percentile = sma_rf_up_spend$Percentile                              
                             , mens = c(0,cumsum(rep(men_total_increase / (nrow(sma_rf_up_spend) - 1), nrow(sma_rf_up_spend) - 1 )) )
                              , womens = c(0,cumsum(rep(women_total_increase / (nrow(sma_rf_up_spend) -1), nrow(sma_rf_up_spend) - 1))) 
                              , max_t = c(0,cumsum(rep(dynamic_total_increase / (nrow(sma_rf_up_spend) -1), nrow(sma_rf_up_spend) - 1)) )
                              ,  Model='Random')



colnames(random_spend)[2] <- colnames(rzp_tree_up_spend)[2] <- colnames(c_forest_up_spend)[2]<- colnames(simple_tree_up_spend)[2] <- colnames(sma_rf_up_spend)[2] <- "Mens E-Mail"
colnames(random_spend)[3] <-colnames(rzp_tree_up_spend)[3] <- colnames(c_forest_up_spend)[3]<- colnames(simple_tree_up_spend)[3] <- colnames(sma_rf_up_spend)[3] <- "Womens E-Mail"
colnames(random_spend)[4] <- "combined"
```


```{r eval=FALSE, include=FALSE}
## Display of results only for SMA models
melt(rbind(
            sma_rf_up_spend[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_up_spend[, c("Percentile","Model","Mens E-Mail")],
            simple_tree_up_spend[, c("Percentile","Model","Mens E-Mail")],
            c_forest_up_spend[, c("Percentile","Model","Mens E-Mail")],
            random_spend[, c("Percentile","Model","Mens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Base Learner",
    title = "All Models - Men's Treatment Curve",
    y = "Cumulated Visits Increase",
    x ="% of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()

melt(rbind(
          sma_rf_up_spend[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_up_spend[, c("Percentile","Model","Womens E-Mail")], 
          simple_tree_up_spend[, c("Percentile","Model","Womens E-Mail")],
          c_forest_up_spend[, c("Percentile","Model","Womens E-Mail")],
          random_spend[, c("Percentile","Model","Womens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Model",
    title = "All Models - Women's Treatment Curve",
    y = "Cumulated Spend Increase",
    x ="% of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_light()


```


```{r}
melt(rbind(
          sma_rf_up_spend[, c("Percentile","Model","combined")], 
          rzp_tree_up_spend[, c("Percentile","Model","combined")], 
          simple_tree_up_spend[, c("Percentile","Model","combined")],
          c_forest_up_spend[, c("Percentile","Model","combined")],
          #simple_forest_up_spend[, c("Percentile","Model","combined")], 
          #rzp_forest_up_spend[, c("Percentile","Model","combined")], 
          random_spend[, c("Percentile","Model","combined")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model, lty= Model), size=1 ) +
  labs(
    color="Model",
    title = "Spend - Male & Female Treatment (Test Data Size: 12,800)",
    y = "Cumulated Spend Increase",
    x ="Amount of Treated"
  ) +
  scale_linetype_manual(values = uplift_lty)+
  scale_color_manual(values = uplift_colors)+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_light()
```



```{r}
# Expected Outcome
melt(rbind(
  sma_rf_exp_spend[, c("Percentile","Model","Expected.Outcome")], 
  rzp_tree_exp_spend[, c("Percentile","Model","Expected.Outcome")], 
  simple_tree_exp_spend[, c("Percentile","Model","Expected.Outcome")], 
  #simple_forest_exp_spend[, c("Percentile","Model","Expected.Outcome")], 
  #rzp_forest_exp_spend[, c("Percentile","Model","Expected.Outcome")], 
  c_forest_exp_spend[, c("Percentile","Model","Expected.Outcome")]
  ), 
  id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=line_size  ) +
  labs(
    color="Model",
    title = "Expected Spend",
    y = "Expected Spend per Customer in USD",
    x ="Amount of Treated"
  ) +
  scale_color_manual(values = exp_colors)+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()
```




## Visit

```{r eval=FALSE, include=FALSE}
# Expected Response per targeted customers
rzp_tree_exp_vis <- read.csv('CSV/rzp_tree_exp_vis.csv')
rzp_tree_up_vis <- read.csv('CSV/rzp_tree_up_vis.csv')

simple_tree_exp_vis <- read.csv('CSV/simple_tree_exp_vis.csv')
simple_tree_up_vis <- read.csv('CSV/simple_tree_up_vis.csv')

c_forest_exp_vis <- read.csv('CSV/c_forest_exp_vis.csv')
c_forest_up_vis <- read.csv('CSV/c_forest_up_vis.csv')

sma_rf_exp_vis <- read.csv('CSV/sma_rf_exp_vis.csv')
sma_rf_up_vis <- read.csv('CSV/sma_rf_up_vis.csv')


sma_rf_exp_vis$Model <- sma_rf_up_vis$Model <- "SMA-RF"
rzp_tree_exp_vis$Model<- rzp_tree_up_vis$Model <- "Rzp-Tree"
simple_tree_exp_vis$Model<- simple_tree_up_vis$Model <- "Rzp-Tree Simple"
c_forest_exp_vis$Model<- c_forest_up_vis$Model <- "Causal-Forest"


dat <- read.csv('Email.csv')
response <- "visit"


dat$men_treatment <- ifelse(dat$segment=='Mens E-Mail',1,0)
dat$women_treatment <- ifelse(dat$segment=='Womens E-Mail',1,0)
dat$control <- ifelse(dat$segment=='No E-Mail',1,0)

# Test data with 5-fold CV
N_test_data <- nrow(dat) * (1/5)

men_total_increase <- (mean(dat[dat$men_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data
women_total_increase <- (mean(dat[dat$women_treatment == 1, response]) - mean(dat[ dat$control == 1, response])) * N_test_data

dynamic_total_increase <- (mean(dat[dat$control == 0, response]) - mean(dat[ dat$control == 1, response]) ) *  N_test_data

random_vis <- data.frame(Percentile = sma_rf_up_vis$Percentile                              
                             , mens = c(0,cumsum(rep(men_total_increase / (nrow(sma_rf_up_vis) - 1), nrow(sma_rf_up_vis) - 1 )) )
                              , womens = c(0,cumsum(rep(women_total_increase / (nrow(sma_rf_up_vis) -1), nrow(sma_rf_up_vis) - 1))) 
                              , max_t = c(0,cumsum(rep(dynamic_total_increase / (nrow(sma_rf_up_vis) -1), nrow(sma_rf_up_vis) - 1)) )
                              ,  Model='Random')


colnames(random_vis)[2] <- colnames(rzp_tree_up_vis)[2] <- colnames(c_forest_up_vis)[2]<- colnames(simple_tree_up_vis)[2] <- colnames(sma_rf_up_vis)[2] <- "Mens E-Mail"
colnames(random_vis)[3] <-colnames(rzp_tree_up_vis)[3] <- colnames(c_forest_up_vis)[3]<- colnames(simple_tree_up_vis)[3] <- colnames(sma_rf_up_vis)[3] <- "Womens E-Mail"
colnames(random_vis)[4] <- "combined"

```

```{r eval=FALSE, include=FALSE}
## Display of results only for SMA models
melt(rbind(
            sma_rf_up_vis[, c("Percentile","Model","Mens E-Mail")], 
            rzp_tree_up_vis[, c("Percentile","Model","Mens E-Mail")],
            simple_tree_up_vis[, c("Percentile","Model","Mens E-Mail")],
            c_forest_up_vis[, c("Percentile","Model","Mens E-Mail")],
            random_vis[, c("Percentile","Model","Mens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Model",
    title = "Men's Treatment",
    y = "Cumulated Visits Increase",
    x ="Amount of Treated"
  ) +
  #scale_x_continuous(limits = (0,1) )+
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()

melt(rbind(
          sma_rf_up_vis[, c("Percentile","Model","Womens E-Mail")], 
          rzp_tree_up_vis[, c("Percentile","Model","Womens E-Mail")], 
          simple_tree_up_vis[, c("Percentile","Model","Womens E-Mail")],
          c_forest_up_vis[, c("Percentile","Model","Womens E-Mail")],
          random_vis[, c("Percentile","Model","Womens E-Mail")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
 # geom_point(aes(y = value, group= Model, color= Model), size=2 ) +
  labs(
    color="Model",
    title = "Women's Treatment",
    y = "Cumulated Visits Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()


melt(rbind(
          sma_rf_up_vis[, c("Percentile","Model","combined")], 
          rzp_tree_up_vis[, c("Percentile","Model","combined")], 
          simple_tree_up_vis[, c("Percentile","Model","combined")],
          c_forest_up_vis[, c("Percentile","Model","combined")],
          random_vis[, c("Percentile","Model","combined")])
     , id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1 ) +
  labs(
    color="Model",
    title = "Both Treatments (Test Data Population: 12,800)",
    y = "Cumulated Conversion Increase",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()
```


```{r eval=FALSE, include=FALSE}
# Expected Outcome
melt(rbind(
  sma_rf_exp_vis[, c("Percentile","Model","Expected.Outcome")], 
  rzp_tree_exp_vis[, c("Percentile","Model","Expected.Outcome")], 
  simple_tree_exp_vis[, c("Percentile","Model","Expected.Outcome")],
  c_forest_exp_vis[, c("Percentile","Model","Expected.Outcome")]
  ), 
  id.vars = c("Percentile","Model")) %>% ggplot(aes(x = Percentile)) +
  geom_line(aes(y = value, group= Model, color= Model), size=1  ) +
  labs(
    color="Model",
    title = "Expected Vists",
    y = "Expected Visit per Customer",
    x ="Amount of Treated"
  ) +
  scale_colour_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_light()
```

